name: ive-pymdp
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - pandas
  - jupyter
  - pytest
  - pip
  - pip:
    - inferactively-pymdp
    - emcee
    - arviz

